Models/APIRegisterItem.cs
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace devLap.Models
{
    public class APIRegisterItem
    {                
        public string wallet_address;
        public string title;
        public string token_type;
        public string thumbnail_url;
        public double token_price;
        public Int64 expire_date;
        public string creator;
        public string description;


    }
}

Models/APIResult.cs
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace devLap.Models
{
    public class APIResult
    {                
        public Int32 code;
        public string message;
        public JObject value;
    }
}

Models/ErrorViewModel.cs
using System;

namespace devLap.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/TutorialsModel.cs
using System;
using System.Collections.Generic;

namespace devLap.Models
{
    public class ImgList
    {
        public Int32 result;
        public string message; 
        public Int32 page_offset;       
        public Int32 page_size;  
        public Int32 total_size;

        public Dictionary<Int64, Item> items = new Dictionary<Int64, Item>();   
    }

    public class Item
    {
        public Int64 item_id;
        public string wallet_address;
        public string title;
        public string token_type;
        public string thumbnail_url;
        public Int64 token_price;
        public Int64 expire_date;
        public Int64 register_date;
        public Int64 creator;
        public string owner_wallet_address;
        public string owner;
        public string token_id;
        public string create_hash;
        public string description;

    }

    public class AddNFT
    {
        public string wallet_address;
        public string title; 
        public string token_type; 
        public Int32 token_price;      
        public string thumbnail_url;  
        public Int64 expire_date;
        public string creator;
        public string description;

    }



}

Controllers/SendController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using devLap.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Net;
using System.IO;
using System.Web;
using devLap.Common;

namespace devLap.Controllers
{
    public class SendController : Controller
    {
        public JsonResult callAPI(bool isPost, string url, string data)
        {        
            APIResult result = new APIResult();
            result.code = -1;

            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(url);
            request.ServerCertificateValidationCallback += (sender, certificate, chain, sslPolicyErrors) => true;
            request.Timeout = 30 * 1000; // 30초
            request.Headers.Add("Accept", "*/*"); // 헤더 추가
            request.Headers.Add("Connection", "keep-alive"); // 헤더 추가
            request.Headers.Add("Accept-Encoding", "gzip, deflate, br"); // 헤더 추가

            if(true == isPost)
            {                
                byte[] sendData = UTF8Encoding.UTF8.GetBytes(data);
                request.Method = "POST";
                request.ContentType = "application/json";
                request.ContentLength = sendData.Length;

                Stream stream = request.GetRequestStream();
                stream.Write(sendData, 0, sendData.Length); 
                stream.Close();
            }
            else
            {
                request.Method = "GET";
            }

            string responseText = string.Empty;
            using (HttpWebResponse response = (HttpWebResponse)request.GetResponse())
            {
                HttpStatusCode status = response.StatusCode;
                Stream responseStream = response.GetResponseStream();
                using (StreamReader streamReader = new StreamReader(responseStream))
                {
                    responseText = streamReader.ReadToEnd();
                    JObject responseData = JObject.Parse(responseText);

                    result.code = (Int32)responseData["return"];
                    result.message = (string)responseData["message"];
                    result.value = (JObject)responseData["value"];
                }
            }

            return Json(JsonConvert.SerializeObject(result));
        }
    }
}

Controllers/SwaggerController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using devLap.Models;

namespace devLap.Controllers
{
    public class SwaggerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/TutorialsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Net;
using System.IO;
using System.Web;
using Microsoft.Extensions.Logging.Abstractions;
using devLap.Common;
using devLap.Models;

namespace devLap.Controllers
{
    public class TutorialsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult List()
        {            
            return View();
        }

        public JsonResult setNFT(string title, string description, string thumbnail_url)
        {
            SendController send = new SendController();

            APIRegisterItem registerItem = new APIRegisterItem();
            registerItem.title = title;
            registerItem.description = description;
            registerItem.thumbnail_url = thumbnail_url;
            
            /* 일단 고정하여 셋팅...*/
            registerItem.wallet_address = "0x9Ec7EDE9204E17dfa34e1d381ED5f49A0D578e96";
            registerItem.token_type = "onit";
            registerItem.token_price = 0.00003;                    

            DateTime expire_date = DateTime.Now.AddDays(30);
            DateTime origin = new DateTime(1970, 1, 1, 0, 0, 0, 0);
            TimeSpan diff = expire_date - origin;

            registerItem.expire_date = (int)Math.Floor(diff.TotalSeconds);
            registerItem.creator = "byDevlap";

            bool isPost = true;              
            string url = APIManager.Instance.FindAPI("RegisterItem");
            string data = JsonConvert.SerializeObject(registerItem);

            JsonResult result = send.callAPI(isPost, url, data);

            return Json(JsonConvert.SerializeObject(result));
        }

        public JsonResult getNFTList(Int32 page_offset, Int32 page_size)
        {
            SendController send = new SendController();
          
            bool isPost = false;
            string url = APIManager.Instance.FindAPI("RequestItemList");
            url = url + "?page_offset="+page_offset+"&page_size="+page_size;
            string data = "";    

            JsonResult result = send.callAPI(isPost, url, data);

            return Json(JsonConvert.SerializeObject(result));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Swagger/Index.cshtml
  <div class="full-size">
    <div class="full-size region-page">
      <div class="flex-column full-size vertical-layout">

          <div class="project-header flex-row flex-noshrink">
            <div class="flex-row flex-grow region-header">
              <a class="commandbar-item suite-logo flex-row flex-noshrink flex-center bolt-link">
                <span aria-hidden="true" class="suite-image commandbar-icon justify-center flex-noshrink fabric-icon">
                </span>
                <span class="brand body-m font-weight-heavy">OnBuff DevLap</span>
              </a>

              <div class="flex-row flex-grow scroll-hidden bolt-breadcrumb-with-items">

                <div class="bolt-breadcrumb-container bolt-breadcrumb-with-items header-breadcrumb flex-grow">
                  <div class="bolt-breadcrumb flex-row flex-grow bolt-breadcrumb-with-items" aria-label="Breadcrumb Item">
                    <div class="bolt-breadcrumb-overflow">
                      <div></div>
                    </div>
                    <div class="bolt-breadcrumb-list-item">
                      <div class="bolt-breadcrumb-item">
                        <a aria-describedby="__bolt-bolt-breadcrumb10-item-described-byCollection" class="bolt-link" data-focuszone="focuszone-391" tabindex="-1">
                          <div class="bolt-breadcrumb-item-text-container">
                            <span class="bolt-breadcrumb-item-text text-ellipsis">onbuff</span>
                          </div>
                          <div class="bolt-breadcrumb-hidden-element" id="__bolt-bolt-breadcrumb10-item-described-byCollection"></div>
                        </a>
                      </div>
                      <div class="bolt-breadcrumb-divider secondary-text cursor-default flex-noshrink">/</div>
                    </div>
                    
                    <div class="bolt-breadcrumb-list-item">
                      <div class="bolt-breadcrumb-item">
                        <a aria-describedby="__bolt-bolt-breadcrumb10-item-described-byCollection" class="bolt-link" data-focuszone="focuszone-391" tabindex="-1">
                          <div class="bolt-breadcrumb-item-text-container">
                            <span class="bolt-breadcrumb-item-text text-ellipsis">ipblock-nft</span>
                          </div>
                          <div class="bolt-breadcrumb-hidden-element" id="__bolt-bolt-breadcrumb10-item-described-byCollection"></div>
                        </a>
                      </div>
                      <div class="bolt-breadcrumb-divider secondary-text cursor-default flex-noshrink">/</div>
                    </div>

                    <div class="bolt-breadcrumb-list-item">
                      <div class="bolt-breadcrumb-item">
                        <a aria-describedby="__bolt-bolt-breadcrumb10-item-described-byCollection" class="bolt-link" data-focuszone="focuszone-391" tabindex="-1">
                          <div class="bolt-breadcrumb-item-text-container">
                            <span class="bolt-breadcrumb-item-text text-ellipsis">swagger</span>
                          </div>
                          <div class="bolt-breadcrumb-hidden-element" id="__bolt-bolt-breadcrumb10-item-described-byCollection"></div>
                        </a>
                      </div>
                      <div class="bolt-breadcrumb-divider bolt-breadcrumb-hidden-element secondary-text cursor-default flex-noshrink">/</div>
                    </div>

                  </div>
                </div>
                    
              </div>

            </div>
          </div>

          <div class="flex-row flex-grow scroll-hidden">
            <div class="navigation-container flex-column">
              <div class="project-navigation region-navigation flex-column flex-grow expanded">

                <!-- side 1st  -->
                <div class="collapsible-section flex-noshrink">
                  <div class="project-item flex-row flex-grow flex-center scroll-hidden">
                    <span class="navigation-icon flex-row flex-center flex-noshrink justify-center">
                      <div class="vss-Persona flex-noshrink project-persona flex-noshrink small" aria-label="ipblock">
                        <img class="vss-Persona-content using-image" 
                          src="https://dev.azure.com/onbuff/_apis/GraphProfile/MemberAvatars/19f4cc99-78ce-44ed-b974-9975f530b8f5?overrideDisplayName=ipblock&amp;size=2" alt="">
                      </div>
                    </span>
                    <span class="font-weight-heavy expanded-only flex-grow text-ellipsis">ipblock-NFT</span>
                  </div>
                </div>
                  <!-- line -->
                  <div class="separator flex-row flex-noshrink"></div>


                <div class="navigation-section flex-column flex-grow scroll-hidden v-scroll-auto custom-scrollbar">
                  <!-- 1st menu -->
                  <div class="hub-group-container flex-column flex-noshrink relative hub-group-only">
                    <div class="flex-row flex-noshrink bolt-expandable-container flex-row flex-center">
                      <a aria-label="Overview" asp-controller="Tutorials" asp-action="Index"
                        class="hub-group navigation-element navigation-link focus-treatment flex-row flex-grow flex-center scroll-hidden relative bolt-link" tabindex="-1">
                        <span class="navigation-icon flex-row flex-center flex-noshrink justify-center">
                          <img alt="" class="contributed-icon contributed-icon-image bolt-image flex-noshrink" 
                            src="https://cdn.vsassets.io/ext/ms.vss-build-web/common-library/Nav-Launch.3tiJhd8JGiL0mrog.png">
                        </span>
                        <span class="navigation-text expanded-only text-ellipsis flex-grow">Tutorials</span>
                      </a>
                    </div>
                  </div>

                  <!-- 2nd menu -->
                  <div class="hub-group-container flex-column flex-noshrink relative expanded-container displayed-container">
                    <div class="flex-row flex-noshrink bolt-expandable-container flex-row flex-center">
                      <a aria-label="Overview" asp-controller="Swagger" asp-action="Index"
                        class="hub-group navigation-element navigation-link focus-treatment flex-row flex-grow flex-center scroll-hidden relative bolt-link" tabindex="-1">
                        <span class="navigation-icon flex-row flex-center flex-noshrink justify-center">
                          <img alt="" class="contributed-icon contributed-icon-image bolt-image flex-noshrink" 
                            src="https://ms.gallerycdn.vsassets.io/extensions/ms/feed/18.186.0.1300478237/1621378091411/common/content/Nav-Feed.png">
                        </span>
                        <span class="navigation-text expanded-only text-ellipsis flex-grow">Swagger</span>
                      </a>
                    </div>
                  </div>

                </div>

                <!-- line --> 
                <div class="separator flex-row flex-noshrink"></div>

                <!-- bottom menu -->
                <div class="collapsible-section flex-noshrink">                
                  <div class="hub flex-row flex-grow flex-center scroll-hidden relative">
                    <span aria-labelledby="__bolt-project-settings-text" role="img">
                      <span class="navigation-icon flex-row flex-center justify-center flex-noshrink"></span>
                    </span>
                    <span class="navigation-text expanded-only text-ellipsis" id="__bolt-project-settings-text"></span>
                  </div>
                  
                  <div onclick="menuChange();" class="hub stand-alone focus-treatment alt-hover-effect flex-row" data-focuszone="focuszone-16" id="project-expansion-toggle" role="button" tabindex="-1">
                    <span id="navigation-arrows" class="navigation-arrows navigation-icon flex-row flex-center flex-noshrink justify-center cursor-pointer flex-noshrink">
                      <div> << </div>
                    </span>
                  </div>
                </div>

              </div>
            </div>

            <!-- right -->
            <div class="flex-column flex-grow scroll-hidden">
                <iframe src="https://onbuff.com:9090" style="width:100vw; height: 100vh"></iframe>
            </div>    
            <!-- //right -->
          </div>

      </div>
    </div>
  </div>

Views/Tutorials/List.cshtml
  <div class="full-size">
    <div class="full-size region-page">
      <div class="flex-column full-size vertical-layout">

          <div class="project-header flex-row flex-noshrink">
            <div class="flex-row flex-grow region-header">
              <a class="commandbar-item suite-logo flex-row flex-noshrink flex-center bolt-link">
                <span aria-hidden="true" class="suite-image commandbar-icon justify-center flex-noshrink fabric-icon">
                </span>
                <span class="brand body-m font-weight-heavy">OnBuff DevLap</span>
              </a>

              <div class="flex-row flex-grow scroll-hidden bolt-breadcrumb-with-items">

                <div class="bolt-breadcrumb-container bolt-breadcrumb-with-items header-breadcrumb flex-grow">
                  <div class="bolt-breadcrumb flex-row flex-grow bolt-breadcrumb-with-items" aria-label="Breadcrumb Item">
                    <div class="bolt-breadcrumb-overflow">
                      <div></div>
                    </div>
                    <div class="bolt-breadcrumb-list-item">
                      <div class="bolt-breadcrumb-item">
                        <a aria-describedby="__bolt-bolt-breadcrumb10-item-described-byCollection" class="bolt-link" data-focuszone="focuszone-391" tabindex="-1">
                          <div class="bolt-breadcrumb-item-text-container">
                            <span class="bolt-breadcrumb-item-text text-ellipsis">onbuff</span>
                          </div>
                          <div class="bolt-breadcrumb-hidden-element" id="__bolt-bolt-breadcrumb10-item-described-byCollection"></div>
                        </a>
                      </div>
                      <div class="bolt-breadcrumb-divider secondary-text cursor-default flex-noshrink">/</div>
                    </div>
                    
                    <div class="bolt-breadcrumb-list-item">
                      <div class="bolt-breadcrumb-item">
                        <a aria-describedby="__bolt-bolt-breadcrumb10-item-described-byCollection" class="bolt-link" data-focuszone="focuszone-391" tabindex="-1">
                          <div class="bolt-breadcrumb-item-text-container">
                            <span class="bolt-breadcrumb-item-text text-ellipsis">ipblock-nft</span>
                          </div>
                          <div class="bolt-breadcrumb-hidden-element" id="__bolt-bolt-breadcrumb10-item-described-byCollection"></div>
                        </a>
                      </div>
                      <div class="bolt-breadcrumb-divider secondary-text cursor-default flex-noshrink">/</div>
                    </div>

                    <div class="bolt-breadcrumb-list-item">
                      <div class="bolt-breadcrumb-item">
                        <a aria-describedby="__bolt-bolt-breadcrumb10-item-described-byCollection" class="bolt-link" data-focuszone="focuszone-391" tabindex="-1">
                          <div class="bolt-breadcrumb-item-text-container">
                            <span class="bolt-breadcrumb-item-text text-ellipsis">tutorials</span>
                          </div>
                          <div class="bolt-breadcrumb-hidden-element" id="__bolt-bolt-breadcrumb10-item-described-byCollection"></div>
                        </a>
                      </div>
                      <div class="bolt-breadcrumb-divider bolt-breadcrumb-hidden-element secondary-text cursor-default flex-noshrink">/</div>
                    </div>

                  </div>
                </div>
                    
              </div>

            </div>
          </div>

          <div class="flex-row flex-grow scroll-hidden">
            <div class="navigation-container flex-column">
              <div class="project-navigation region-navigation flex-column flex-grow expanded">

                <!-- side 1st  -->
                <div class="collapsible-section flex-noshrink">
                  <div class="project-item flex-row flex-grow flex-center scroll-hidden">
                    <span class="navigation-icon flex-row flex-center flex-noshrink justify-center">
                      <div class="vss-Persona flex-noshrink project-persona flex-noshrink small" aria-label="ipblock">
                        <img class="vss-Persona-content using-image" 
                          src="https://dev.azure.com/onbuff/_apis/GraphProfile/MemberAvatars/19f4cc99-78ce-44ed-b974-9975f530b8f5?overrideDisplayName=ipblock&amp;size=2" alt="">
                      </div>
                    </span>
                    <span class="font-weight-heavy expanded-only flex-grow text-ellipsis">ipblock-NFT</span>
                  </div>
                </div>
                  <!-- line -->
                  <div class="separator flex-row flex-noshrink"></div>


                <div class="navigation-section flex-column flex-grow scroll-hidden v-scroll-auto custom-scrollbar">
                  <!-- 1st menu -->
                  <div class="hub-group-container flex-column flex-noshrink relative expanded-container displayed-container">
                    <div class="flex-row flex-noshrink bolt-expandable-container flex-row flex-center">
                      <a aria-label="Overview" asp-controller="Tutorials" asp-action="Index"
                        class="hub-group navigation-element navigation-link focus-treatment flex-row flex-grow flex-center scroll-hidden relative bolt-link" tabindex="-1">
                        <span class="navigation-icon flex-row flex-center flex-noshrink justify-center">
                          <img alt="" class="contributed-icon contributed-icon-image bolt-image flex-noshrink" 
                            src="https://cdn.vsassets.io/ext/ms.vss-build-web/common-library/Nav-Launch.3tiJhd8JGiL0mrog.png">
                        </span>
                        <span class="navigation-text expanded-only text-ellipsis flex-grow">Tutorials</span>
                      </a>
                    </div>
                  </div>

                  <!-- 2nd menu -->
                  <div class="hub-group-container flex-column flex-noshrink relative hub-group-only">
                    <div class="flex-row flex-noshrink bolt-expandable-container flex-row flex-center">
                      <a aria-label="Overview" asp-controller="Swagger" asp-action="Index"
                        class="hub-group navigation-element navigation-link focus-treatment flex-row flex-grow flex-center scroll-hidden relative bolt-link" tabindex="-1">
                        <span class="navigation-icon flex-row flex-center flex-noshrink justify-center">
                          <img alt="" class="contributed-icon contributed-icon-image bolt-image flex-noshrink" 
                            src="https://ms.gallerycdn.vsassets.io/extensions/ms/feed/18.186.0.1300478237/1621378091411/common/content/Nav-Feed.png">
                        </span>
                        <span class="navigation-text expanded-only text-ellipsis flex-grow">Swagger</span>
                      </a>
                    </div>
                  </div>

                </div>

                <!-- line --> 
                <div class="separator flex-row flex-noshrink"></div>

                <!-- bottom menu -->
                <div class="collapsible-section flex-noshrink">                
                  <div class="hub flex-row flex-grow flex-center scroll-hidden relative">
                    <span aria-labelledby="__bolt-project-settings-text" role="img">
                      <span class="navigation-icon flex-row flex-center justify-center flex-noshrink"></span>
                    </span>
                    <span class="navigation-text expanded-only text-ellipsis" id="__bolt-project-settings-text"></span>
                  </div>
                  
                  <div onclick="menuChange();"; class="hub stand-alone focus-treatment alt-hover-effect flex-row" data-focuszone="focuszone-16" id="project-expansion-toggle" role="button" tabindex="-1">
                    <span id="navigation-arrows" class="navigation-arrows navigation-icon flex-row flex-center flex-noshrink justify-center cursor-pointer flex-noshrink">
                      <div> << </div>
                    </span>
                  </div>
                </div>

              </div>
            </div>

            <!-- right -->
            <div class="flex-column flex-grow scroll-hidden">

              <!-- contents -->
                <div class="v-scroll-auto flex flex-grow relative region-content">
                    <div class="main">
                        <!-- main > head -->
                        <div class="head">                            
                            <div class="cd-title-bar-breadcrumb-container dtc-bread-crumb-component">
                                <ol class="list-42">
                                    <li class="listItem-43">
                                        <a class="itemLink-50" tabindex="0">
                                            <div>Tutorials</div>
                                        </a>
                                        <i> > </i>
                                    </li>
                                    <li class="listItem-43">
                                        <span class="item-48">
                                            <div>
                                                List
                                            </div>
                                        </span>
                                    </li>
                                </ol>                        
                            </div>                            
                        </div>
                        <!-- //main > head -->

                        <!-- main > body -->
                        <div class="body">
                            <div class="dtc-workflow-pivot pivot-fabric-style-overrides">
                                <div>
                                    <!--sub menu-->
                                    <ul class="root-40 root_4edb0ad9" role="tablist">
                                        <button type="button" onclick="location.href='@Url.Action("Index", "Tutorials")'" class="link_4edb0ad9" tabindex="0">
                                        <div><span>Add</span></div>

                                        <button type="button" onclick="location.href='@Url.Action("List", "Tutorials")'" class="link_4edb0ad9 linkIsSelected_4edb0ad9" tabindex="0">
                                        <div><span>List</span></div>
                                    </ul>
                                    <!--//sub menu-->
                                    <div class="dtc-pivot-item">
                                        <div class="cd-canvas-tab-content">
                                            <div class="overlay-left-section">                                                
                                                <div class="cd-canvas-container">
                                                  <div class="overlay-left-section">
                                                    <table class="type09">
                                                      <thead>
                                                        <tr>
                                                          <th scope="cols">ID</th>
                                                          <th scope="cols">Title</th>
                                                          <th scope="cols">NFT</th>
                                                          <th scope="cols">Description</th>
                                                          <th scope="cols">State</th>
                                                          <th scope="cols">Owner</th>
                                                        </tr>
                                                      </thead>
                                                      <tbody id="items">
                                                      </tbody>
                                                    </table>
                                                    <div class="paging relative" id="paging"></div>
                                                  </div>
                                                </div>            
                                            </div>                                    
                                        </div>
                                    </div>                                
                                </div>
                            </div>
                        </div>
                        <!-- //main > body -->


                    </div>  
                </div>
              <!-- //contents -->
              
            </div>
            <!-- //right -->
          </div>

      </div>
    </div>
  </div>

<script>

  let page_id = 1;
  let page_size = 10;
  let page_length = 10;
  let total_page_count = 0;

  window.onload=function(){
    getNFT(page_id, page_size);
  }

</script>